spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/restaurantdb
    password:  secret
    username:  root

eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka